### ISSUE TITLE
Какая-то ошибка :D

### ISSUE THREAD

**Issue by domik25** [dogekiller21/ViKtor_Music_Bot#3]
Traceback (most recent call last):
  File "C:\Users\comp\Desktop\music_bot\ViKtor_Music_Bot\__main__.py", line 88, in <module>
    client.load_extension(f"{cogs_path}.{filename[:-3]}")
  File "C:\Users\comp\Desktop\music_bot\ViKtor_Music_Bot\venv\lib\site-packages\discord\cog.py", line 732, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\comp\Desktop\music_bot\ViKtor_Music_Bot\venv\lib\site-packages\discord\cog.py", line 663, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.music' raised an error: ModuleNotFoundError: No module named 'vkwave'

(venv) C:\Users\comp\Desktop\music_bot\ViKtor_Music_Bot>

**Comment by dogekiller21** [comment]
`pip install vkwave` Должно помочь ;)
Попробуй гуглить ошибки перед тем, как открывать обсуждения, пожалуйста

**Comment by domik25** [comment]
Извиняюсь, но какого вида должен быть токен от vk? 
Пишет что-то с токеном не так

**Comment by dogekiller21** [comment]
Что пишет?
